### PR TITLE
Performs the Minimax Algorithm on a set of outcomes

### PR DESCRIPTION
**Pull request by dshunter107**
Here is my implementation of the Minimax algorithm. I also tested it. I am not sure if I need to put more tests in, but that was all I could think of. Let me know if you have any suggestions.

### CODE REVIEW

**Comment by dshunter107** [comment]
closes Issue #149

**Comment by dshunter107** [comment]
Hello. was this what you were looking for?

**Review by Samyssmile — CHANGES_REQUESTED** [review]
I have reviewed the proposed implementation of the Minimax algorithm in the pull request and, after careful consideration, I cannot approve it in its current form. Here's a summary of my reasons:

1. **Lack of Tree Structure and Recursion**: The Minimax algorithm typically operates on a tree structure representing different game states. This implementation treats outcomes as a flat list, ignoring the essential tree structure of games.

2. **No Adjustable Depth**: The implementation does not allow for adjusting the search depth, a common feature in Minimax to explore the game tree up to a certain level.

3. **No Heuristic Evaluation Functions**: There are no mechanisms for customizable heuristic evaluation functions, which are necessary for complex games where exploring the entire game tree is impractical.

4. **Missing Move Generation and State Transitions**: The code lacks mechanisms for generating moves or managing state transitions, which are crucial for applying Minimax in game scenarios.

5. **Insufficient Error Handling**: Potential runtime errors, such as an empty list of outcomes, are not adequately addressed.

To approve the pull request, these issues should be addressed to ensure a complete and flexible implementation of the Minimax algorithm.

**Comment by dshunter107** [comment]
okay. back to the drawing board. I will look into changing it to meet the requirements

**Pull request closed without merging**
